[manager]

append_keymap = [
  { on = [
    "c",
    "z",
  ], run = """ shell 'printf "Your Name:"; read name; sed -E "s| ?$PWD|\\" \\".|g;s|^..||;s|$|\\"|g" <<<$@ | xargs zip -r "$name.zip"' --block --confirm """, desc = "Create zip archive" },
  { on = [
    "c",
    "t",
  ], run = """ shell 'printf "Your Name:"; read name; sed -E "s| ?$PWD|\\" \\".|g;s|^..||;s|$|\\"|g" <<<$@ | xargs tar czf "$name.tar.gz"' --block --confirm """, desc = "Create tar archive" },
  { on = [
    "e",
  ], run = """ shell '$EDITOR "$@"' --block --confirm """, desc = "Open with $EDITOR" },
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = "R", run = "plugin --sync hide-preview", desc = "Hide or show preview" },
  { on = "T", run = "plugin --sync max-preview", desc = "Maximize or restore preview" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
]

[input]

append_keymap = [
  { on = [
    "q",
  ], run = "close", desc = "Cancel input" },
  { on = [
    "<C-j>",
  ], run = "escape", desc = "Go back the normal mode, or cancel input" },
  { on = [
    "X",
  ], run = [
    "move -1",
    "delete --cut",
    "move 1 --in-operating",
  ], desc = "Cut the before current character" },
]
